### ISSUE TITLE
ETL pipeline for ICGC

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#10]
**Background**: The [International Cancer Genome Consortium (ICGC)](https://icgc.org/) is an scientific consortium for collaboration among the world's leading cancer genomics researchers. The [ICGC Data Portal](https://dcc.icgc.org/) aggregates cancer genomics data from its consortium member projects, including [The Cancer Genome Atlas (TCGA)](http://cancergenome.nih.gov/) projects. While the cBioPortal has all the TCGA projects, we haven't integrated many of the ICGC projects from other sources.

**Goal**: Building a public ETL (Extract, Transform, and Load) pipeline for ICGC data.

**Approach**: 
- Extract data from the [ICGC Data Portal](https://dcc.icgc.org/).
- Transform the extracted data to the [cBioProtal file formats](https://github.com/cBioPortal/cbioportal/wiki/File-Formats)
- (Optional) Improve our load pipeline.

**Need skills**: Bioinformatics, Java, Spring Batch

**Possible mentors**: [Benjamin Gross](https://github.com/n1zea144), [Zack Heins](https://github.com/zheins)

**Comment by sameer9311** [comment]
Hi @jjgao and @n1zea144 , I am excited about the project idea and would like to contribute to it as a part of my gsoc 2016 project. Can you provide me a starting point or a link to the code repo to get well acquainted with the project ?

**Comment by n1zea144** [comment]
Well, there is no code written yet, but what we would like is to convert genomic data files found at the ICGC.  For example, the breast data found here:
[https://dcc.icgc.org/api/v1/download?fn=/current/Projects/BRCA-US/simple_somatic_mutation.open.BRCA-US.tsv.gz](https://dcc.icgc.org/api/v1/download?fn=/current/Projects/BRCA-US/simple_somatic_mutation.open.BRCA-US.tsv.gz)  (the file is simple_somatic_mutation.open.BRCA-US.tsv) should be converted to the cBioPortal  mutation file format:
[https://github.com/cBioPortal/cbioportal/wiki/File-Formats#mutation-data](https://github.com/cBioPortal/cbioportal/wiki/File-Formats#mutation-data) using spring batch.

**Comment by zulrich91** [comment]
Hi @jjgao , @n1zea144 
I am equally interested in this project, but hope I am not late to start discussions as I will like to work on this project during the Google Summer of Code for this year

I just need some confirmation and I will like to start discussions with the mentors for potential milestones that could be trashed for the accomplishment of this project within the 12 coding weeks of gsoc. 

As for resources I will just follow with what @n1zea144 gave in his previous comment 

Thanks

**Comment by zulrich91** [comment]
Greetings.

@jjgao and @n1zea144 please comment from you will be welcomed.. I followed the resources you suggested and some more others and now I have some questions for you which will help us in defining the content of my proposal. 

Thanks.

**Comment by n1zea144** [comment]
Hi @zulrich91 Please ask questions as needed.

**Comment by zulrich91** [comment]
@n1zea144 
Thanks for the reply, My questions are as follows

How is data from the TCGA extracted ? 

I ask this question because the only way I could figure out for extracting data from the ICGC Data portal is a manual process, where by one has to search the available repositories and download a manifest that suits his choice. I thought knowing how TCGA data is extracted could be of help. 

Should in case the data will be downloaded manually how will this be uploaded ? Will it require a GUI or the scope of the project does not require this ?

I wish to know the scope of the transformation ? Will a transformation be done for each of the  12 available data formats ? 

Will a transformation consist of generating 4 files(a datafile, its meta data file, cancer_type.txt and meta_study.txt ) ? from each file extracted from the ICGC Data portal ?

I submitted a draft proposal lately yesterday, i will appreciate you review so that we come out with a feasible final proposal. 

Thanks.

**Comment by n1zea144** [comment]
Hi @zulrich91,

I can understand why you would like to know how TCGA pipeline works in order to model ICGC pipeline.  Unfortunately, TCGA data is more consistent that ICGC data so automating data fetching is not as straightforward.  In fact, the version of TCGA data that is currently imported into cBioPortal is provided by Broad Firehose and fetched using "firehose_get" bash script.

Given the frequency by which ICGC data comes out, I imagine that preselected projects from the [icgc-projects-page](https://dcc.icgc.org/releases/current/Projects) can be downloaded to a predefined location that can then be fed as a resources into a Spring-Batch reader.

A GUI is not required - the Spring Batch jobs should be runnable via the command line.

Each ICGC project should result in multiple data files that conform to cBioPortal file format (although its possible some ICGC project may only have mutation data for example), a corresponding meta data file, and a meta_study file.

**Comment by zulrich91** [comment]
Hi @n1zea144 ,
Thanks for these comments they have clarified my doubts as I was thinking of
           Automation => GUI 
                    OR
CommandLineJobRunner=> Resources

**Comment by zulrich91** [comment]
Hi @n1zea144,

Yesterday, I Shared the draft proposal with cBioPortal via the GSoC portal, I wish you review that and  comment for modifications.

Thanks.

**Comment by shivanshsoni** [comment]
Hi @jjgao and @n1zea144 , I am interested in this  project idea and would like to contribute to it as a part of my gsoc 2017 project. Can you please provide me the link of repo to get acquaintd with this project?
