### ISSUE TITLE
Integrate Precision Cancer KnowledgeBase (CivicDB) into cBioPortal

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/GSoC#16]
**Background**:  [Clinical Interpretations in Cancer (CiVIC)](https://civic.genome.wustl.edu/#/home) is an open source / open-access knowledge base for precision cancer medicine.  Curators contribute knowledge about specific genes and specific variants in cancer, and all data is available via an [open API](https://civic.genome.wustl.edu/#/api-documentation).

**Goal**: Extend the current patient view within the cBioPortal to include annotations from CivicDB.  

[Example](http://www.cbioportal.org/case.do?cancer_study_id=ucec_tcga_pub&case_id=TCGA-BK-A0CC) of the current patient view:

![screenshot_668](https://cloud.githubusercontent.com/assets/1009066/12875515/5f4c2c4a-cdba-11e5-936e-eb57ea26a636.png)

We are open to any ideas on how to best do this, and how to best visualize.

**Needed Skills**: Bioinformatics, Java, Javascript.

**Possible Mentor**:  Ethan Cerami

**Comment by tj-513** [comment]
Hi , I'm comfortable with java , JavaScript. However , I lack knowledge on bioinformatics. Is it possible for me to contribute to this project in google summer of code 2016? If so, from where should I get started?

**Comment by kkumar12** [comment]
Hi, i am a student of IT and have bioinformatics as additional subject  i think i can do this project.My college is Cluster Innovation Center (DU)

**Comment by ashishtiwarigsoc** [comment]
@ecerami I am interested in cBioPortal and would like to work on this task. I have been working to setup local build environment to understand and play around with codebase, and have succeeded in most part. I am stuck at installing the seed database. Download was breaking with browser so I did the download with wget. Now, I am not able to unzip the seed file (cbioportal-seed.sql). Since, the database tables are not created, portal homepage complains. I also see exception on tomcat's log about the same (which makes sense).

Also, is this the best place to ask questions or I should prefer mailing-list or email (which I do not know).

Thanks
Ashish

**Comment by ashishtiwarigsoc** [comment]
@ecerami 
Looking at the a sample API call (https://civic.genome.wustl.edu/api/genes/5), I am wondering which information is relevant for "Annotation" column?

**Comment by ecerami** [comment]
@tj-513:  apologies for the delay in writing back.  For this specific project, you would need some basic bioinformatics experience.

**Comment by ecerami** [comment]
@ashishtiwarigsoc:  for general questions about installation, best place to start or restart is the wiki pages, which we have recently updated.  https://github.com/cBioPortal/cbioportal/wiki

**Comment by ecerami** [comment]
@ashishtiwarigsoc:  my suggestion is to first familiarize yourself with the entire CivicDB web site, starting here:  https://civic.genome.wustl.edu/#/help/introduction

**Comment by jas1994** [comment]
@ecerami Submitted my proposal.Eagerly awaiting for feedback!!
