### ISSUE TITLE
Clients to the new JSON based web API

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#21]
**Background**: Currently we have [R and Matlab clients](http://www.cbioportal.org/cgds_r.jsp) to connect to the current text based web API. We are developing our next version [JSON based web API](https://github.com/cBioPortal/cbioportal/wiki/The-API-and-API-Client-%5BBeta%5D) and would like develop our next versions of clients as well connecting to the new web API.

**Goal**: To develop a new clients (R, Javascript, Java, Python, Matlab, Python) that connects to our next version JSON-based web API for retrieving data from cBioPortal.

**Approach**: We will use [Swagger](http://swagger.io/) to spec our JSON based API. One option is to generate most of the clients with Swagger tools, but it has to be evaluated.

Some useful links:
- [New API doc](https://github.com/cBioPortal/cbioportal/wiki/cBioPortal-Web-API)
- [Swagger UI to the new API](http://www.cbioportal.org/beta/swagger-ui.html#!/api-controller/)
- [New API entry points](https://github.com/cBioPortal/cbioportal/blob/master/web/src/main/java/org/mskcc/cbio/portal/web/ApiController.java)
- [New API root](http://www.cbioportal.org/api/)
- [Current R client](http://www.cbioportal.org/cgds_r.jsp) and [its code](https://github.com/cBioPortal/cgdsr)
- [Current Matlab client code](https://github.com/cBioPortal/matlab)

**Notes**:
- Currently, R, Matlab, and Python clients are the most important for us.
- We already have a [JS client](https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/js/api/cbioportal-client.js), which needs to be separated from the main code base to a standalone NPM package.
- Java client would be nice to have but not a must-have.
- Feel free to propose clients for your favorite languages.

**Need skills**: JSON, Web API, R, Javascript, Java, Python, Matlab, Python. (Doesn't have to familiar with all.)

**Possible mentors**: [JJ Gao](https://github.com/jjgao)

**Comment by jinankjain** [comment]
I would like to work on this project.

@jjgao, Could you please tell me some startup bugs so that I could get familiar with the code base.

**Comment by jjgao** [comment]
@jinankjain I just added a few links in the description. A good start point is to understand the structure of the new API. If you are familiar with R, you could try to reimplement some of the functions in the current R Client (cgds-r) with the new API. You could also do that in other languages.

**Comment by akshayjain007** [comment]
@jjgao I would like to work on this project.
I want to develop a python client if that is fine.

**Comment by rbute** [comment]
@jjgao can I contribute java based client?

**Comment by atishay100495** [comment]
@jjgao I am very excited about this project and would love to make a contribution. I have good command over Java, Python, REST API, J2EE, git, Matlab, Octave, JSON, XML and am familiar with R and Javascript too. I have familiarized myself with the new API and would like to start working on a basic Java based client first. I have already come up with a design and will try to implement a basic Java based client in a few days for your review.

**Comment by jinankjain** [comment]
@jjgao I have started making a python client https://github.com/jinankjain/cBioPortal/blob/master/Python/cgds.py Could you please review it. Am I on right track ?

**Comment by atishay100495** [comment]
@jjgao After 2 days of continuous work, I've finally completed creating a highly robust and extensible Java Client framework for CGDS. Currently, I've only added  support for getCancerTypes(). Other endpoints and methods can be plugged into the framework very easily and I'll be adding them soon. Please review the framework here: https://github.com/atishay100495/cgds-java
Ease of use can be established by viewing and running the test class (instructions for running are provided in README.md): https://github.com/atishay100495/cgds-java/blob/master/src/test/java/org/cbioportal/cgds_java/tests/CGDSJavaAPITest.java
I've learnt a LOT during this exercise. Please provide your feedback or suggestions for improvements.

**Comment by jjgao** [comment]
Thanks to everyone who expressed interest in this project. I have added some links and notes to to clarify a few things. Since we have about 3 months of coding time and there are already a lot of prior work, we hope to finish more than two clients after summer in this project.

**Comment by jinankjain** [comment]
@jjgao Yes we would able to finish clients in atleast in 4 different languages

**Comment by atishay100495** [comment]
@jjgao The Java client will only take a few more days to complete fully. Then, I'll try to get started with clients in other languages as well.

**Comment by atishay100495** [comment]
@jjgao Can you please clarify the following doubt?
The following endpoint is returning an empty list:
http://www.cbioportal.org/api/geneticprofiledata?genetic_profile_ids=brca_tcga_pub_log2CNA&genes=BRCA1

However, the API Doc shows that this genetic profile data should be present:
{
    "genetic_profile_id":"brca_tcga_pub_log2CNA",
    "entrez_gene_id":672,
    "hugo_gene_symbol":"BRCA1",
    "sample_id":"TCGA-A1-A0SB-01",
    "study_id":"brca_tcga_pub",
    "profile_data":"0.044"
}

The endpoint is expected to return the above json response but it is returning an empty list.

**Comment by atishay100495** [comment]
@jjgao I found a few inconsistencies in the API Doc. Can you please update it for the following:
1. /api/geneticprofiledata
There are 2 additional fields present in the REST response which are not updated in the API Doc for Mutation profiles:
a) "protein_start_position"
b) "protein_end_position"
Sample response:
{
    "genetic_profile_id": "brca_tcga_pub_mutations",
    "entrez_gene_id": "672",
    "hugo_gene_symbol": "BRCA1",
    "sample_id": "TCGA-A2-A0D2-01",
    "study_id": "brca_tcga_pub",
    "sequencing_center": "genome.wustl.edu",
    "mutation_status": "Germline",
    "mutation_type": "Frame_Shift_Del",
    "validation_status": "Unknown",
    "amino_acid_change": "V1713*",
    "functional_impact_score": "NA",
    "xvar_link": "NA",
    "xvar_link_pdb": "NA",
    "xvar_link_msa": "NA",
    "chr": "17",
    "start_position": "41215906",
    "end_position": "41215906",
    **"protein_start_position": "1713",**
    **"protein_end_position": "1713",**
    "reference_allele": "C",
    "variant_allele": "-",
    "reference_read_count_tumor": "-1",
    "variant_read_count_tumor": "-1",
    "reference_read_count_normal": "-1",
    "variant_read_count_normal": "-1"
  }

2. /api/samplelists
The field "patient_ids" should be "sample_ids" in the API Doc.
Sample Response:
{
    "id": "acc_tcga_all",
    "name": "All Tumors",
    "description": "All tumor samples (92 samples)",
    "study_id": "acc_tcga",
    "**sample_ids**": [
      "TCGA-OR-A5J1-01",
      "TCGA-OR-A5J2-01",
      "TCGA-OR-A5J3-01",
.....
   ]
}

**Comment by jjgao** [comment]
@atishay100495: good catch. ```brca_tcga_pub_log2CNA ``` was removed lately. The following profile should work.

http://www.cbioportal.org/api/geneticprofiledata?genetic_profile_ids=brca_tcga_pub_gistic&genes=BRCA1

**Comment by atishay100495** [comment]
@jjgao Thanks for the clarification. 
I am nearing completion of the Java Client for CGDS. After that, I would like to add support for running the tests directly from an Ant target instead of depending on the testng plugin for Eclipse which would make it easier for others to run the tests. This will take a day or two. Then, we can deploy/upload the version 1.0 of the jar file to maven repository(http://mvnrepository.com/). This will allow anyone to download our jar over the internet or simply mention it as a dependency for their project to make use of the CGDS java client. This will also need a day or two as I haven't deployed an artifact to maven repository before.

**Comment by jjgao** [comment]
@atishay100495: Thanks for the update. Please hold off uploading to maven repo. At this moment, a high quality proposal to gsoc is very important.

**Comment by atishay100495** [comment]
@jjgao Thanks for the information. I will get started on it. It would be very helpful if you can provide some guidelines and suggestions for a good quality GSoC proposal.

**Comment by jjgao** [comment]
@atishay100495 A high quality proposal should break the task into sub-tasks and propose solutions for each sub-task with a detailed timeline.

**Comment by atishay100495** [comment]
@jjgao Thanks for the tip. I will keep this in mind while drafting my gsoc proposal.

**Comment by atishay100495** [comment]
@jjgao There is a small inconsistency in the API Doc for Sample Lists
The option 'sample_list_ids' should be 'sample_ids'. Can you please update it?

I have one more doubt. How does the filtering for the following endpoint work?
http://www.cbioportal.org/api/genes?hugo_gene_symbol=CDKN2AP16INK4A
This is returning results which do not even have the hugo_gene_symbol=CDKN2AP16INK4A. Is this expected? I have seen a few more endpoints with similar behavior.

**Comment by atishay100495** [comment]
@jjgao I have effectively completed the Java Client for CGDS. The tests can be viewed here:
https://github.com/atishay100495/cgds-java/blob/master/src/test/java/org/cbioportal/cgds_java/tests/CGDSJavaAPITest.java

The current test output and results can be downloaded using this link:
https://docs.google.com/uc?authuser=0&id=0B15Tsm1HLWRJTGtKYkF0VlJXTG8&export=download

Now the only remaining issue is to create an Ant target to allow users to easily run the tests.
https://github.com/atishay100495/cgds-java/issues/1

Please provide your feedback for any improvements.

I am planning to hold off work on the CGDS clients now till Mar 15 and will now concentrate on creating a good GSoC proposal.

**Comment by jjgao** [comment]
@atishay100495 it's a good idea to focus on writing the proposal now.

**Comment by tamimcsedu19** [comment]
@atishay100495 I found out that replacing 'hugo_gene_symbol' with 'hugo_gene_symbols' returns the correct result. 

http://www.cbioportal.org/api/genes?hugo_gene_symbols=CDKN2AP16INK4A

**Comment by atishay100495** [comment]
@tamimcsedu19 Thank you for the clarification

**Comment by jjgao** [comment]
I just update a few links:

- [New API doc](https://github.com/cBioPortal/cbioportal/wiki/cBioPortal-Web-API)
- [Swagger UI to the new API](http://www.cbioportal.org/beta/swagger-ui.html#!/api-controller/getCancerTypes)

**Comment by atishay100495** [comment]
@jjgao Thank you for sharing the links. After some detailed research into the Swagger API and Swagger Codegen, I think we should generate most of the CGDS API clients (Java, Python, Javascript, Ruby) using the Swagger Codegen tool. This way we'll be able to conform to a general API client design for all the supported languages and if there is any change on the server side, the clients can be regenerated without the need to modify all the supported clients. This will reduce the client-library maintenance tremendously. Another advantage would be that the documentation will also be kept in sync with the client code. Swagger codegen does not support generating clients for R and Matlab and these clients can be created independently. Please let me know your views on the same or if you would prefer generating independent clients for all required languages instead of using Swagger codegen.

**Comment by jjgao** [comment]
@atishay100495 Sounds like a good plan!

**Comment by atishay100495** [comment]
@jjgao I have shared my GSoC proposal draft on the GSoC website. Can you please review it and provide your comments for any changes or improvements?

**Comment by Bharath95** [comment]
Hi,
I have been following this project and would like to contribute for the same, I did couple of things and have a couple of questions for you so that it eases out my writing of a GSoC proposal.
1. New API doc : The current web api does not expose the RESTful services, whereas Revised Web API does expose the RESTful service.The Revised Web API is still under development. Am I correct? 
2. Swagger UI to the new API : I checked the Swagger UI of the new API and tested it with given examples. This list would get populated as and when we start finishing the Revised Web API.
3.I have installed swagger code gen and swagger UI and trying to generate a python client from it for cBioPortal. As soon as I am done I would send it to you on github.
4. I cloned the R client and have it run on the local system.In the new R client I could see only some of the services being consumed whereas the old R client for the current web api consumes all the webservices. Am I on correct track ?
5.Current Matlab code I am having problems , it does not work with MAtlab version r2016a

**Comment by atishay100495** [comment]
@jjgao I've added more details for the implementation plan as asked in the GSoC proposal. Please let me know if more details are needed.

**Comment by jjgao** [comment]
@Bharath95: thanks for your interest. Please see my comments below. 
1. Yes.
2. Yes.
3. OK.
4. We may deprecate some APIs from the old one (such as the ones related to RPPA) if that is what you are asking.
5. That could be a good issue to be fixed :)
6. Sure. But keep in mind we only one 3 months.

**Comment by atishay100495** [comment]
@jjgao I have successfully setup and built Swagger Codegen on my machine and used to generate CGDS client libraries for Java and Python. The links are provided below:
https://github.com/atishay100495/swagger-cgds-java
https://github.com/atishay100495/swagger-cgds-python

However, there are some issues that need to be fixed for the auto-generated clients. The generated client methods are not named appropriately. Many of the overloaded methods have '1' appended to them (Eg. getCancerTypes1, getGenes1). These will need some advanced configuration in Swagger and require to be fixed so that the methods are generated appropriately.

**Comment by Bharath95** [comment]
@jjgao   https://github.com/Bharath95/cbioportal-pyclient  This is the link for python client generated using swagger-codegen using cbioportal's rest api.

**Comment by atishay100495** [comment]
@jjgao The GSoC proposal needs to submitted finally within 2 days. Can you please do a final review of the draft before I upload the pdf?

**Comment by atishay100495** [comment]
@jjgao I will not be able to work on the project actively this week due to examinations in college

**Comment by Bharath95** [comment]
Is this project still up? i'd like to work on it.

**Comment by Yasara123** [comment]
@jjgao Can I contribute to this project still now?
