### ISSUE TITLE
Integrate MolecularMatch clinical trials data into cBioPortal

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#23]
**Background**: 
[MolecularMatch](https://www.molecularmatch.com/) provides a resource for matching clinical trials based on a patient's cancer type and molecular data. The cBioPortal (http://www.cbioportal.org/) is a research resource for cancer genomics. One of the challenges is to interpret the great amount of genomic data it has accumulated. We have integrated a few resources, including OncoKB, MyCancerGenome, and CancerHotspot.org in the annotation column in the mutation table ([an example](http://www.cbioportal.org/case.do?cancer_study_id=skcm_tcga&sample_id=TCGA-D3-A51N-06)). It would be useful to link to clinical trials too for each mutation.

![image](https://cloud.githubusercontent.com/assets/840895/22567576/769dacdc-e95e-11e6-956f-5f79ef688d3e.png)

**Goal**: 

Linking clinical trials from MolecularMatch for mutations and copy number events in the cBioPortal on both patient view page and mutations tab in results page. One requirement is that the loading has to be quick.

**Approach**: 

- Connecting to [MolecularMatch API](https://api.molecularmatch.com/) using cancer type, gene, and alteration to retrieve clinical trials. 
- We may need to work with MolecularMatch engineers if the performance of API cannot support real-time application.

**Need skills**: 

- Javascript
- Java
- Web API

**Possible mentors**: 
@jjgao

**Comment by Thuva4** [comment]
Hi @jjgao 
I am interested in this project. I have worked with  Javascript , Java and web API in my past projects. Do you have any warm-up tasks for the project? How should I start?

**Comment by jjgao** [comment]
@Thuva4 getting familiar with the cBioPortal (cbioportal.org) and its codebase (https://github.com/cBioPortal/cbioportal) and MolecularMatch API (https://api.molecularmatch.com/) would be a good start. Please let us know if you have specific questions.

**Comment by stefanches7** [comment]
Hello, @jjgao,

as far as I understand what's really crucial in this issue is really speed of loading.
Therefore: how close would it be possible to work with Molecular Match engineers, to which grade could the API be adapted to be quick especially for requests we need?
Does cBioPortal has any restrictions/capabilities on distant calls such those to Molecular Match?

Thanks!

**Comment by Shane-Neeley** [comment]
Hi @stefanches7 , @jjgao , @Thuva4 I’m an engineer at MolecularMatch. Response time is about 1-2sec (see status.molecularmatch.com) because the data packets for trials are pretty big. So you don't want to do those calls when you load a cBioPortal page. 
You could pre-formulate the query when you load the page. Then hovering/clicking an icon on each row could perform the trial search for that mutation/CNA and then you’ll have the JSON trial data to work with. 
I am a mentor for this GSoC project. The API also has drugs, publications, detailed mutation annotations, assertion evidence. Thx!
Shane

**Comment by msc-jinal** [comment]
Hi,

I study about this issue, Here is my idea to achieve this requirements.

I am thinking, the use of Ajax based asynchronous call with pre-formulated queries. When page load, all queries formulated and queued for API service call, but page will load without waiting response from MolecularMatch. This way page loaded smoothly, but when response received from server call, the results with be replaced in table with help of javascript.

Because, I dont think, we can speed up MolecularMatch, as we dont have control over there.

Thanks.
Jinal

**Comment by Shane-Neeley** [comment]
Hey @msc-jinal that's a good idea. Do you plan on submitting a proposal to GSoC?

**Comment by msc-jinal** [comment]
Hi,

I was thinking to submit proposal in GSoC, but now submission is closed.
Do you think, still I can write proposal and submit?

I am interested to implement this project. Let me know if any
possibility/alternative way to work on this project.

Regards,
Jinal
