### ISSUE TITLE
Pipeline to extract and transform GDC data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#24]
**Background**: 

[The NCI's Genomic Data Commons (GDC)](https://gdc.cancer.gov/) provides the cancer research community with a unified data repository across cancer genomic studies. GDC has provided multiple ways (web, tools, API) to access the data. It would be very useful to build a pipeline to retreive data from GDC and import them into the cBioPortal database.

**Goal**: 

Building a public ET (Extract, Transform) pipeline for GDC data.

**Approach**: 

- Extract data from the [GDC Data Portal](https://gdc-portal.nci.nih.gov/).
- Transform the extracted data to the [cBioProtal file formats](https://github.com/cBioPortal/cbioportal/wiki/File-Formats)
- (Optional) Improve our load pipeline.

**Need skills**:

Bioinformatics, Java, Spring Batch

**Possible mentors**:

[Benjamin Gross](https://github.com/n1zea144), [Zack Heins](https://github.com/zheins), [Angelica Ochoa](https://github.com/angelicaochoa)

**Comment by dorianb96** [comment]
Hi, 

I am a student very interested in this GSOC project.

The general idea of the project seems very clear, but for writing a proposal I would probably need to focus on the exact implementation details. 

Is there a contact point I could ask for more details about this project?

WIth regards,
Dorian.

**Comment by boratonAJ** [comment]
Hi,

I am a masters student, and I am interested in this idea. Would like to work this. Thanks

**Comment by TheLayman** [comment]
@jjgao I'm new to cBioPortal. I have prior experience in Java and Automation. Can you please guide me through the setting up process and all?

**Comment by n1zea144** [comment]
hi @TheLayman Our online docs is the best place to start, section 2. cBioPortal Deployment.

[https://cbioportal.readthedocs.io/en/latest/](https://cbioportal.readthedocs.io/en/latest/)

**Comment by stefanches7** [comment]
Hello, dear contributors as well as mentors,

this idea sounds interesting for me, especially because it's so tightely coupled with bioinformatics, which I love so much.

Anything but "improve our load pipeline" seems to be clear: which pipeline exactly is mentioned here? What exactly does it load? 

Kind regards,
Stefan.

**Comment by DixitPatel** [comment]
Hello @n1zea144,
If I am not mistaken, building the basic batch framework (Job Workflow) would be a part of the scope as well ? ( In addition to implementing Service endpoint to get GDC data ) 
Also for importing the data from GDC, is there a scope on how many primary sites need to be considered ? Since there are ~16 file formats mentioned [here](https://cbioportal.readthedocs.io/en/latest/File-Formats.html). I am concerned on how we might be able to transform 'all' the data from GDC to these formats.

**Comment by jjgao** [comment]
@DixitPatel: As all pipeline work, some basic workflow will be necessary, but the code to convert different data format is more important. For this project, the end goal is to be able to extract data from GDC and transform them into the cBioPortal format.

For your second question, TCGA / GDC has most of these data. It would be useful to find what's available in GDC and list them in pair with the cBioPortal files.
